# Generated by Django 4.2.2 on 2023-06-26 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('area', models.IntegerField()),
                ('cultivation_pattern', models.CharField(max_length=10)),
                ('creation_date', models.DateField()),
                ('edit_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('description', models.TextField()),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden.garden')),
            ],
        ),
        migrations.CreateModel(
            name='Cultivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivation_date', models.DateField()),
                ('piece_number', models.IntegerField()),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden.garden')),
            ],
        ),
    ]
