# Generated by Django 4.2.2 on 2023-06-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0003_alter_garden_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivation',
            name='piece_number',
            field=models.PositiveIntegerField(),
        ),
    ]
